version: '2'
services:
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8071:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./etc:/etc/odoo
      - ./project:/mnt/extra-addons
    tty: true
    # command: -- -d mobile_wallet_api -u mobile_wallet_api
    # To run test, use command below
    command: -- -d mobile_wallet -u mobile_wallet_api --test-enable
    restart: always
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  odoo-web-data:
  odoo-db-data:
